version: "1"

services:
  bot:
    build: .
    network_mode: "host"
    restart: always

  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "bot_db"
      POSTGRES_USER: "rebuke_33"
      POSTGRES_PASSWORD: "praise33"
      network_mode: "host"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - .:/var/lib/postgresql/data
    ports:
      - "5432:5432"